openapi: 3.0.0
tags:
  - name: Index
get:
  description: None
responses:
    '200':
      description: Success
    '400':
      description: Bad Request
    '500':
      description: Internal Server Error