openapi: 3.0.0
tags:
  - name: load document content from link
get:
  link: (str) link that provides PDF document
responses:
    '200':
      description: Success
    '400':
      description: Bad Request
    '500':
      description: Internal Server Error