openapi: 3.0.0
tags:
  - name: load document content from gcs
get:
  blob: (str) filename that inside in the cloud platform
responses:
    '200':
      description: Success
    '400':
      description: Bad Request
    '500':
      description: Internal Server Error